### ISSUE TITLE
Unable to connect to bitbake server

### ISSUE THREAD

**Issue by pietrushnic** [3mdeb/yocto-docker#27]
Did you faced something like this?

```
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection...
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection...
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection...
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection...
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection...
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection...
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection...
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection...
ERROR: Unable to connect to bitbake server, or start one
```

**Comment by macpijan** [comment]
@pietrushnic  I might have at some point in the past, but cannot say anything specific. Was it a one-time issue?

**Comment by pietrushnic** [comment]
@macpijan this thing happen when 2 containers are running. I just left first with `ctrl-c` and tried to run second. I'm not sure if we can protect ourselves against that.

**Comment by macpijan** [comment]
@pietrushnic  This seems to happen when you interrupt the build (`Ctrl+C`) when running container in the noninteractive mode (`-i` flag). In such a case, the container may still be running (see `docker ps`) and should be killed first. It did not happen before, there interactive mode was present. The interactive mode was disabled to allow build in CI (e.g. Jenkins). Running with noninteractive mode is not so pleasant for local development. Maybe we should distinguish those 2 scenarion.

**Comment by pietrushnic** [comment]
@macpijan minimal solution is to let use know in `Known issues section` about this problem, other solution is to kill remaining containers before running next one. IMO secon option is ok since we expect to have only one container in system that do Yocto build.

**Comment by fangxlmr** [comment]
I encountered the same issue while using Yocto, but I have no clue on the reason behind and how to solve it.

**Comment by pietrushnic** [comment]
@fangxlmr temporary solution is simple, just list running containers and stop the one that is in background, then You can start again. IMO we should solve that in a robust way - we will get to that.

**Comment by cdm0413** [comment]
I just met the same issue, remove the bitbake.lock in the build path, and run again, it will works

**Comment by Pallapu454** [comment]
Hello, 
I am using Arago distribution, i tried to remove bitbake.lock, but i still get the same issue and again this bitbake.lock file is keep getting generated. 

I have even restarted my PC also.

**Comment by macpijan** [comment]
@TomaszAIR Easy fix would be to keep the `i` flag when not running in CI.

**Comment by Mohana493** [comment]
> Did you faced something like this?
> 
> ```
> NOTE: Reconnecting to bitbake server...
> NOTE: Retrying server connection...
> NOTE: Reconnecting to bitbake server...
> NOTE: Retrying server connection...
> NOTE: Reconnecting to bitbake server...
> NOTE: Retrying server connection...
> NOTE: Reconnecting to bitbake server...
> NOTE: Retrying server connection...
> NOTE: Reconnecting to bitbake server...
> NOTE: Retrying server connection...
> NOTE: Reconnecting to bitbake server...
> NOTE: Retrying server connection...
> NOTE: Reconnecting to bitbake server...
> NOTE: Retrying server connection...
> NOTE: Reconnecting to bitbake server...
> NOTE: Retrying server connection...
> ERROR: Unable to connect to bitbake server, or start one
> ```

How to fix it??

**Comment by Mohana493** [comment]
By removing bitbake .lock files also it's not executing

**Comment by macpijan** [comment]
We do not really use this repo anymore, please take a look at the description in the `about` section.
I wil lgo ahead and archive it

```
This repository is not currently used. For yocto projects we use https://github.com/siemens/kas container 
```
